### ISSUE TITLE
Module not found: Can't resolve '../profile.json' in 'C:\Users\iwina\Projects\ClubHousePC\clubhouse-client\src\components'

### ISSUE THREAD

**Issue by RallyCreatorCoins** [tomaspavlin/clubhouse-client#1]
![chrome_itjpQSkopF](https://user-images.githubusercontent.com/74742333/108945463-45fb6100-7622-11eb-8252-d69123c176ec.png)

@tomaspavlin Hey brother - Thanks for putting together this tool! I'm stuck on this error, can't get passed it.. Any ideas?

Do you have Discord by chance? Taking paid development bounties by chance? :)

**Comment by RallyCreatorCoins** [comment]
I was able to fix the above error by copy/pasting the profile.json file into the \components folder.

**Comment by tomaspavlin** [comment]
@RallyCreatorCoins Hi, I fixed the issue. Now it works without need for copy/pasting the file. My Discord account is `Tomaspavlin#2182`.
