### ISSUE TITLE
Localhost not working

### ISSUE THREAD

**Issue by ishanraval** [tomaspavlin/clubhouse-client#4]
Hi - Not sure whether it's a problem with the client or my system. Everything (login, yarn start) is working until the last step, opening localhost:3000. At that step, the browser just says "this site can't be reached."
On doing yarn start, the message is: 

> yarn run v1.22.5
> $ node ./bin/www
> Initializing Clubhouse client
>   sfa-p#clubhouse-api:client initiated new client identified by B9309815-309C-48EE-9903-705D188B4AFD +0ms
>   api:server Listening on port 9000 +0ms

So then I also tried to run localhost:9000. That gives the error:

> Applying Clubhouse client values previously computed
> ClientError [NotFoundError]: Not Found
>     at /usr/share/clubhouse-client-master/api/app.js:31:8
>     at Layer.handle [as handle_request] (/usr/share/clubhouse-client-master/api/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/usr/share/clubhouse-client-master/api/node_modules/express/lib/router/index.js:317:13)
>     at /usr/share/clubhouse-client-master/api/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/usr/share/clubhouse-client-master/api/node_modules/express/lib/router/index.js:335:12)
>     at next (/usr/share/clubhouse-client-master/api/node_modules/express/lib/router/index.js:275:10)
>     at /usr/share/clubhouse-client-master/api/node_modules/express/lib/router/index.js:635:15
>     at next (/usr/share/clubhouse-client-master/api/node_modules/express/lib/router/index.js:260:14)
>     at Function.handle (/usr/share/clubhouse-client-master/api/node_modules/express/lib/router/index.js:174:3)
>     at router (/usr/share/clubhouse-client-master/api/node_modules/express/lib/router/index.js:47:12)
> GET / 404 4.820 ms - 1096

Am running Ubuntu 19.04, but also tried it through Termux on my Android device, and it runs into the same problem.
My apologies if I'm making a very basic mistake and there isn't actually an issue with your code; I'm not the most code-savvy.

**Comment by tomaspavlin** [comment]
Did you also install and run frontend in root directory? You need to make sure you are in *clubhouse-client* directory and then install and run using:

```
yarn install
yarn start
```

**Comment by ishanraval** [comment]
No no, that was fine. But I solved the problem. It had to do with my npm package/compatability. Thanks!

**Comment by ksuhr1** [comment]
Hello can you tell me what you did to solve this?
